# Generated by Django 3.1 on 2021-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
