# Generated by Django 3.1 on 2021-07-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_auto_20210711_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Community_image',
            field=models.ImageField(blank=True, upload_to='photos/Communities'),
        ),
    ]
